# Generated by Django 5.2.14 on 2026-06-02 11:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goats", "0002_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccinationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        help_text="Days between doses — used to compute next_due_date."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["vaccine_name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("interval_days__gt", 0)),
                        name="vaccinationschedule_interval_days_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination"),
                            ("deworming", "Deworming"),
                            ("checkup", "Checkup"),
                            ("treatment", "Treatment"),
                            ("injury", "Injury"),
                            ("pregnancy", "Pregnancy"),
                            ("note", "Note"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("record_date", models.DateField()),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("administered_by", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="goats.goat",
                    ),
                ),
                (
                    "vaccination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_records",
                        to="health.vaccinationschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "record_type__in",
                                [
                                    "vaccination",
                                    "deworming",
                                    "checkup",
                                    "treatment",
                                    "injury",
                                    "pregnancy",
                                    "note",
                                ],
                            )
                        ),
                        name="healthrecord_type_valid",
                    )
                ],
            },
        ),
    ]
