# Generated by Django 5.2.14 on 2026-06-02 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum number of goats this area should hold."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gt", 0)),
                        name="area_capacity_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Goat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag_number", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("deceased", "Deceased"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goats",
                        to="goats.area",
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dam_offspring",
                        to="goats.goat",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sired_offspring",
                        to="goats.goat",
                    ),
                ),
            ],
            options={
                "ordering": ["tag_number"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sex__in", ["M", "F"])),
                        name="goat_sex_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["active", "sold", "deceased", "quarantined"],
                            )
                        ),
                        name="goat_status_valid",
                    ),
                ],
            },
        ),
    ]
