# Generated by Django 5.2.14 on 2026-06-02 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goats", "0002_qrcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaTransferLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("related", "Related"),
                            ("closely_related", "Closely related"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("transferred_at", models.DateTimeField(auto_now_add=True)),
                ("transferred_by", models.CharField(max_length=120)),
                (
                    "from_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="goats.area",
                    ),
                ),
                (
                    "goat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_logs",
                        to="goats.goat",
                    ),
                ),
                (
                    "to_area",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_in",
                        to="goats.area",
                    ),
                ),
            ],
            options={
                "ordering": ["-transferred_at"],
            },
        ),
    ]
